_target_: model.HyperNetWithAlexNet
in_shape: [32,32,3] # Tensorflow format
no_classes_per_task: 10
activation_function:
  _target_: torch.nn.ReLU
hnet_hidden_layers: [100,50]
hnet_embedding_size: 512