_target_: model.HyperNetWithResNet18
in_shape: [64,64,3] # Tensorflow format
no_classes_per_task: 5
num_feature_maps: [16, 64, 128, 256]
activation_function:
  _target_: torch.nn.ReLU
hnet_hidden_layers: [100]
hnet_embedding_size: 48