defaults:
  - _self_
  - dataset: split_cifar_100
  - model: alexnet_wo_hnet
  - method: ewc
  - exp: interval_training_wo_hnets

fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1
  accelerator: cpu # or gpu

wandb:
  entity: ${oc.env:WANDB_ENTITY}
  project: ${oc.env:WANDB_PROJECT}