run_func:
    _target_: experiment.calc_ver_accuracy
seed: 42
log_dir: # set during runtime to automatically created dir
epsilon: 0.00784313725

path_to_mixup_weights: saved_models/split_mini_imagenet/full_architecture_with_mixup/42
path_to_weights: saved_models/split_mini_imagenet/full_architecture/1