run_func:
    _target_: experiment.calc_ver_accuracy
seed: 1
log_dir: # set during runtime to automatically created dir
epsilon: 0.0001

path_to_mixup_weights: outputs/2025-07-13/15-03-40
path_to_weights: outputs/2025-07-13/15-03-40