run_func:
    _target_: experiment.calc_ver_accuracy
seed: 42
log_dir: # set during runtime to automatically created dir
epsilon: 0.01

path_to_mixup_weights: /home/patrykkrukowski/Projects/SHIELD/saved_models/permuted_mnist/mixup/linear
path_to_weights: saved_models/permuted_mnist/full_architecture/4