run_func:
    _target_: experiment.inc_no_iterations_pgd
seed: 1
log_dir: # set during runtime to automatically created dir
no_splits: 10
max_steps: 200

attack:
    pgd:
        _target_: attack.PGD
        eps: 0.00392156862  
        alpha: 0.015686274509 
        random_start: True
path_to_mixup_weights: saved_models/split_cifar_100/full_architecture_with_mixup/0
path_to_hnet_weights: saved_models/split_cifar_100/hnet/