method: grid
metric:
  name: avg_acc
  goal: maximize

parameters:

  # Dataset (fixed)
  dataset._target_:
    value: continual_dataset.RotatedMNIST
  dataset.number_of_tasks:
    value: 10
  dataset.validation_size:
    value: 5000
  dataset.padding:
    value: 2

  # Experiment setup
  exp.seed:
    value: 42
  exp.batch_size:
    values: [64,128]
  exp.no_epochs:
    value:
  exp.no_iterations:
    value: 5000

  # Fabric setup
  fabric.accelerator:
    value: gpu

  # Method (sweep these)
  method.lr:
    value: 0.001
  method.beta:
    values: [0.0005, 0.001, 0.005, 0.01, 0.05]
  method.mixup_alpha:
    values: [0.01, 0.1, 0.2, 0.3, 0.4, 0.5]
  method.epsilon:
    values: [0.00784313725, 0.0784313725, 0.09803921568, 0.01]
  method.use_lr_scheduler:
    value: False
  method._target_:
    value: method.SHIELD

  # Model
  model._target_:
    value: model.HyperNetWithMLP
  model.in_shape:
    value: 1024
  model.no_classes_per_task:
    value: 10
  model.activation_function._target_:
    value: torch.nn.ReLU
  model.hnet_hidden_layers:
    values: [[100, 100], [100, 50], [200, 50]]
  model.target_hidden_layers:
    value: [256, 256]
  model.hnet_embedding_size:
    values: [24, 48, 96]

  # W&B logging
  wandb.entity:
    value: ${oc.env:WANDB_ENTITY}
  wandb.project:
    value: ${oc.env:WANDB_PROJECT}

command:
  - ${env}
  - python
  - src/main.py
  - --config-name
  - shield.yaml
  - ${args_no_hyphens}
