method: grid
metric:
  name: avg_acc
  goal: maximize

parameters:

  dataset:
    value: split_cub_200
  method:
    value: shield
  model:
    value: vit

  # Dataset (fixed)
  dataset._target_:
    value: continual_dataset.SplitCUB200
  dataset.number_of_tasks:
    value: 20
  dataset.validation_size:
    value: 0
  
  # Experiment setup
  exp.seed:
    value: 42
  exp.batch_size:
    value: 32
  exp.no_epochs:
    value: 500
  exp.no_iterations:
    value:

  # Fabric setup
  fabric.accelerator:
    value: gpu

  # Method (sweep these)
  method.lr:
    value: 0.001
  method.beta:
    values: [0.01, 0.05, 0.1]
  method.mixup_alpha:
    values: [0.0, 0.01, 0.1, 0.2]
  method.epsilon:
    values: [1.0, 10.0, 100.0, 1000.0]
  method.use_lr_scheduler:
    value: False
  method.mixup_epsilon_decay:
    value: linear
  method._target_:
    value: method.SHIELD

  # Model
  model._target_: 
    value: model.HyperNetWithPretrainedViT
  model.no_classes_per_task: 
    value: 10
  model.activation_function._target_:
   value: torch.nn.ReLU
  model.hnet_hidden_layers: 
    values: [[100], [100,100], [200]]
  model.target_hidden_layers:
    value: [1000, 1000]
  model.hnet_embedding_size:
    values: [128, 256, 512]



  # W&B logging
  wandb.entity:
    value: ${oc.env:WANDB_ENTITY}
  wandb.project:
    value: ${oc.env:WANDB_PROJECT}

command:
  - ${env}
  - python
  - src/main.py
  - --config-name
  - shield.yaml
  - ${args_no_hyphens}
